// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegistryAccountRequest struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Method               string   `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistryAccountRequest) Reset()         { *m = RegistryAccountRequest{} }
func (m *RegistryAccountRequest) String() string { return proto.CompactTextString(m) }
func (*RegistryAccountRequest) ProtoMessage()    {}
func (*RegistryAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *RegistryAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistryAccountRequest.Unmarshal(m, b)
}
func (m *RegistryAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistryAccountRequest.Marshal(b, m, deterministic)
}
func (m *RegistryAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistryAccountRequest.Merge(m, src)
}
func (m *RegistryAccountRequest) XXX_Size() int {
	return xxx_messageInfo_RegistryAccountRequest.Size(m)
}
func (m *RegistryAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistryAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegistryAccountRequest proto.InternalMessageInfo

func (m *RegistryAccountRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegistryAccountRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegistryAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegistryAccountRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type RegistryAccountResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistryAccountResponse) Reset()         { *m = RegistryAccountResponse{} }
func (m *RegistryAccountResponse) String() string { return proto.CompactTextString(m) }
func (*RegistryAccountResponse) ProtoMessage()    {}
func (*RegistryAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *RegistryAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistryAccountResponse.Unmarshal(m, b)
}
func (m *RegistryAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistryAccountResponse.Marshal(b, m, deterministic)
}
func (m *RegistryAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistryAccountResponse.Merge(m, src)
}
func (m *RegistryAccountResponse) XXX_Size() int {
	return xxx_messageInfo_RegistryAccountResponse.Size(m)
}
func (m *RegistryAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistryAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegistryAccountResponse proto.InternalMessageInfo

func (m *RegistryAccountResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegistryAccountResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type VerifyAccountRequest struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Method               string   `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Verifycode           int32    `protobuf:"varint,5,opt,name=verifycode,proto3" json:"verifycode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyAccountRequest) Reset()         { *m = VerifyAccountRequest{} }
func (m *VerifyAccountRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyAccountRequest) ProtoMessage()    {}
func (*VerifyAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *VerifyAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyAccountRequest.Unmarshal(m, b)
}
func (m *VerifyAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyAccountRequest.Marshal(b, m, deterministic)
}
func (m *VerifyAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyAccountRequest.Merge(m, src)
}
func (m *VerifyAccountRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyAccountRequest.Size(m)
}
func (m *VerifyAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyAccountRequest proto.InternalMessageInfo

func (m *VerifyAccountRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *VerifyAccountRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *VerifyAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *VerifyAccountRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *VerifyAccountRequest) GetVerifycode() int32 {
	if m != nil {
		return m.Verifycode
	}
	return 0
}

type VerifyAccountResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyAccountResponse) Reset()         { *m = VerifyAccountResponse{} }
func (m *VerifyAccountResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyAccountResponse) ProtoMessage()    {}
func (*VerifyAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *VerifyAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyAccountResponse.Unmarshal(m, b)
}
func (m *VerifyAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyAccountResponse.Marshal(b, m, deterministic)
}
func (m *VerifyAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyAccountResponse.Merge(m, src)
}
func (m *VerifyAccountResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyAccountResponse.Size(m)
}
func (m *VerifyAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyAccountResponse proto.InternalMessageInfo

func (m *VerifyAccountResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *VerifyAccountResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type LoginAccountRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAccountRequest) Reset()         { *m = LoginAccountRequest{} }
func (m *LoginAccountRequest) String() string { return proto.CompactTextString(m) }
func (*LoginAccountRequest) ProtoMessage()    {}
func (*LoginAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *LoginAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAccountRequest.Unmarshal(m, b)
}
func (m *LoginAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAccountRequest.Marshal(b, m, deterministic)
}
func (m *LoginAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAccountRequest.Merge(m, src)
}
func (m *LoginAccountRequest) XXX_Size() int {
	return xxx_messageInfo_LoginAccountRequest.Size(m)
}
func (m *LoginAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAccountRequest proto.InternalMessageInfo

func (m *LoginAccountRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginAccountRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type LoginAccountResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAccountResponse) Reset()         { *m = LoginAccountResponse{} }
func (m *LoginAccountResponse) String() string { return proto.CompactTextString(m) }
func (*LoginAccountResponse) ProtoMessage()    {}
func (*LoginAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *LoginAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAccountResponse.Unmarshal(m, b)
}
func (m *LoginAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAccountResponse.Marshal(b, m, deterministic)
}
func (m *LoginAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAccountResponse.Merge(m, src)
}
func (m *LoginAccountResponse) XXX_Size() int {
	return xxx_messageInfo_LoginAccountResponse.Size(m)
}
func (m *LoginAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAccountResponse proto.InternalMessageInfo

func (m *LoginAccountResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginAccountResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LoginAccountResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutAccounRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutAccounRequest) Reset()         { *m = LogoutAccounRequest{} }
func (m *LogoutAccounRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutAccounRequest) ProtoMessage()    {}
func (*LogoutAccounRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{6}
}

func (m *LogoutAccounRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutAccounRequest.Unmarshal(m, b)
}
func (m *LogoutAccounRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutAccounRequest.Marshal(b, m, deterministic)
}
func (m *LogoutAccounRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutAccounRequest.Merge(m, src)
}
func (m *LogoutAccounRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutAccounRequest.Size(m)
}
func (m *LogoutAccounRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutAccounRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutAccounRequest proto.InternalMessageInfo

func (m *LogoutAccounRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutAccountResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutAccountResponse) Reset()         { *m = LogoutAccountResponse{} }
func (m *LogoutAccountResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutAccountResponse) ProtoMessage()    {}
func (*LogoutAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{7}
}

func (m *LogoutAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutAccountResponse.Unmarshal(m, b)
}
func (m *LogoutAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutAccountResponse.Marshal(b, m, deterministic)
}
func (m *LogoutAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutAccountResponse.Merge(m, src)
}
func (m *LogoutAccountResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutAccountResponse.Size(m)
}
func (m *LogoutAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutAccountResponse proto.InternalMessageInfo

func (m *LogoutAccountResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LogoutAccountResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// 测试token
type TestAccountRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestAccountRequest) Reset()         { *m = TestAccountRequest{} }
func (m *TestAccountRequest) String() string { return proto.CompactTextString(m) }
func (*TestAccountRequest) ProtoMessage()    {}
func (*TestAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{8}
}

func (m *TestAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestAccountRequest.Unmarshal(m, b)
}
func (m *TestAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestAccountRequest.Marshal(b, m, deterministic)
}
func (m *TestAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestAccountRequest.Merge(m, src)
}
func (m *TestAccountRequest) XXX_Size() int {
	return xxx_messageInfo_TestAccountRequest.Size(m)
}
func (m *TestAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestAccountRequest proto.InternalMessageInfo

func (m *TestAccountRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type TstAccountResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TstAccountResponse) Reset()         { *m = TstAccountResponse{} }
func (m *TstAccountResponse) String() string { return proto.CompactTextString(m) }
func (*TstAccountResponse) ProtoMessage()    {}
func (*TstAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{9}
}

func (m *TstAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TstAccountResponse.Unmarshal(m, b)
}
func (m *TstAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TstAccountResponse.Marshal(b, m, deterministic)
}
func (m *TstAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TstAccountResponse.Merge(m, src)
}
func (m *TstAccountResponse) XXX_Size() int {
	return xxx_messageInfo_TstAccountResponse.Size(m)
}
func (m *TstAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TstAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TstAccountResponse proto.InternalMessageInfo

func (m *TstAccountResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TstAccountResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*RegistryAccountRequest)(nil), "account.RegistryAccountRequest")
	proto.RegisterType((*RegistryAccountResponse)(nil), "account.RegistryAccountResponse")
	proto.RegisterType((*VerifyAccountRequest)(nil), "account.VerifyAccountRequest")
	proto.RegisterType((*VerifyAccountResponse)(nil), "account.VerifyAccountResponse")
	proto.RegisterType((*LoginAccountRequest)(nil), "account.LoginAccountRequest")
	proto.RegisterType((*LoginAccountResponse)(nil), "account.LoginAccountResponse")
	proto.RegisterType((*LogoutAccounRequest)(nil), "account.LogoutAccounRequest")
	proto.RegisterType((*LogoutAccountResponse)(nil), "account.LogoutAccountResponse")
	proto.RegisterType((*TestAccountRequest)(nil), "account.TestAccountRequest")
	proto.RegisterType((*TstAccountResponse)(nil), "account.TstAccountResponse")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x6d, 0xda, 0x26, 0xd6, 0x01, 0x41, 0xc6, 0xb6, 0x96, 0x68, 0x6b, 0xd9, 0x93, 0x28, 0xf4,
	0xa0, 0x37, 0xa1, 0x88, 0x1e, 0x44, 0x41, 0x10, 0x42, 0xf1, 0x5e, 0xd3, 0xb5, 0x86, 0xb6, 0xd9,
	0xba, 0xbb, 0x51, 0xbc, 0xfb, 0x25, 0xfe, 0xa6, 0x17, 0xc9, 0x6e, 0xb2, 0xa4, 0x4d, 0x22, 0xd4,
	0x8b, 0xb7, 0xcc, 0xbe, 0xc7, 0xcc, 0x7b, 0xfb, 0x66, 0x03, 0x3b, 0x63, 0xdf, 0x67, 0x51, 0x28,
	0x07, 0x4b, 0xce, 0x24, 0xc3, 0xad, 0xa4, 0x24, 0x9f, 0x16, 0xb4, 0x3d, 0x3a, 0x0d, 0x84, 0xe4,
	0x1f, 0x57, 0xfa, 0xcc, 0xa3, 0xaf, 0x11, 0x15, 0x12, 0x5d, 0x68, 0x84, 0x81, 0x3f, 0x0b, 0xc7,
	0x0b, 0xda, 0xb1, 0xfa, 0xd6, 0xf1, 0xb6, 0x67, 0xea, 0x18, 0x8b, 0x04, 0xe5, 0x0a, 0xab, 0x6a,
	0x2c, 0xad, 0x63, 0x6c, 0x39, 0x16, 0xe2, 0x9d, 0xf1, 0x49, 0xa7, 0xa6, 0xb1, 0xb4, 0xc6, 0x36,
	0x38, 0x0b, 0x2a, 0x5f, 0xd8, 0xa4, 0x53, 0x57, 0x48, 0x52, 0x91, 0x4b, 0xd8, 0xcf, 0xa9, 0x10,
	0x4b, 0x16, 0x0a, 0x8a, 0x08, 0x75, 0x9f, 0x4d, 0xb4, 0x04, 0xdb, 0x53, 0xdf, 0xb8, 0x0b, 0xb5,
	0x85, 0x98, 0x26, 0x93, 0xe3, 0x4f, 0xf2, 0x65, 0x41, 0xf3, 0x91, 0xf2, 0xe0, 0xf9, 0x1f, 0x5d,
	0x60, 0x0f, 0xe0, 0x4d, 0x69, 0x50, 0x82, 0x6d, 0x25, 0x38, 0x73, 0x42, 0x86, 0xd0, 0x5a, 0xd3,
	0xb8, 0x91, 0x47, 0x0a, 0x7b, 0xf7, 0x6c, 0x1a, 0x84, 0x79, 0x87, 0xc6, 0x85, 0xf5, 0x8b, 0x8b,
	0x6a, 0xa9, 0x8b, 0xda, 0x4a, 0x16, 0x1e, 0x34, 0x57, 0xc7, 0x6c, 0x22, 0x12, 0x9b, 0x60, 0x4b,
	0x36, 0xa3, 0x61, 0xd2, 0x54, 0x17, 0xe4, 0x54, 0x49, 0x67, 0x91, 0xd4, 0x4d, 0x53, 0xe9, 0x86,
	0x6c, 0x65, 0xc9, 0x43, 0x68, 0x65, 0xc9, 0x9b, 0x5e, 0xd3, 0x09, 0xe0, 0x88, 0x0a, 0xb9, 0x76,
	0x4b, 0xc5, 0xa3, 0x2e, 0x00, 0x47, 0xe2, 0x6f, 0x73, 0xce, 0xbe, 0xab, 0x90, 0x3e, 0x23, 0x7c,
	0x80, 0x06, 0x4f, 0xf6, 0x17, 0x8f, 0x06, 0xe9, 0x5b, 0x2b, 0x7e, 0x58, 0x6e, 0xbf, 0x9c, 0xa0,
	0x05, 0x90, 0x0a, 0xde, 0x81, 0xa3, 0x17, 0x07, 0xbb, 0x86, 0x5d, 0xb4, 0xdf, 0x6e, 0xaf, 0x0c,
	0x36, 0xad, 0x6e, 0xc0, 0x9e, 0xc7, 0x79, 0xe2, 0xa1, 0xa1, 0x16, 0xac, 0x91, 0xdb, 0x2d, 0x41,
	0x4d, 0x9f, 0x5b, 0x70, 0xe6, 0x2a, 0x96, 0xd5, 0x46, 0xeb, 0xa1, 0x66, 0x14, 0x15, 0xa6, 0x48,
	0x2a, 0x78, 0x0d, 0x75, 0x19, 0x67, 0x72, 0x60, 0x98, 0xf9, 0xc0, 0xdc, 0x0c, 0x28, 0xf2, 0x3d,
	0x9e, 0x1c, 0xf5, 0x23, 0x3b, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x70, 0x7f, 0x9d, 0xbb, 0xd9,
	0x04, 0x00, 0x00,
}
